import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'velvet-serenity-sofa',
    name: 'Sofa Sérénité en Velours',
    category: 'Living Room',
    subCategory: 'SALON — ASSISES',
    price: 4850,
    description: 'Façonné avec la précision d\'une sculpture architecturale, le Sofa Sérénité en Velours incarne le summum du Quiet Luxury. Sa forme monolithique est adoucie par un velours italien à haute densité, offrant une expérience tactile incomparable pour votre sanctuaire contemporain.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqcbGURHZPwT73C398k_N5_DnIHJAyI3NI1mU4MV97VJBIBS4sqbqaWO6E2EEIM9FC6gO7VbTn5mhWjFsODrQuvpJIqtHDz0eNZMC4wXWLXtjUeQ7Go3N8Cq4FDjFz9oQh3F54kbQNgYnt-ZDGvV8vAHEElk8IxPZ_A8y7SSR2mqzzG1o8Nf8JMl3LywnAsce57ZiNXBuzOAlOB4uqjuD2waIRgzsfvWfhUL8lxW6q9VVBg3lU63IihXjI2b2vVZuhwOFjsrZEJ_Nl',
    additionalImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuB0XzwKB-YuBlSkVwNNNombN9SuxAoCgf-Ic5Z-gTQk7gQ0CJmzSq3NxbT7PGFjLoVtCO03JIl0uxH0-bgwnrCBTri7Pn_7oaevZQ9Qr2jBbiFK3IdImotI4ZnzLQuHBGJvVHS7kUWG0YPi_tXuq6FXz6ATXb6QMsDP6w_qvzBMg-iff8mDErYtLvJ0aa0RyJBacbm3hF_DbNcH_XGmZ9MhhKjm_qvifh80XqRLFDcPHVJP7gm3-fIQNP3VSU2CPdDg5xh8Sag_p3sI',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBIICOBi5IbKJ2spEy-knFNd8CzbZUZl_JAJOj-E4qDczpo-yMs8yVrynHXm7e-PyTZMz9I7a8V2ETlLFna7fwH5njveAUELNEfwkmKg6Xk-Rf-HmBR60-hNP3f3UiuTeGwHtqHFfE6edCbS9S4FRatHiJlcO3IDpebhGD1kxypwmeHf2kRta6O1JQLu6QVladd5oJqHbqwnofhpqm3Jop4oc9rekqfb8ZwIUZq1wwMLNc2ckR6Ozuf6q0bUIlIARzfCuYQBWL6EMLj'
    ],
    fabrics: [
      { id: 'emerald', name: 'Velours Émeraude Profond', hex: '#1B2621', previewUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqcbGURHZPwT73C398k_N5_DnIHJAyI3NI1mU4MV97VJBIBS4sqbqaWO6E2EEIM9FC6gO7VbTn5mhWjFsODrQuvpJIqtHDz0eNZMC4wXWLXtjUeQ7Go3N8Cq4FDjFz9oQh3F54kbQNgYnt-ZDGvV8vAHEElk8IxPZ_A8y7SSR2mqzzG1o8Nf8JMl3LywnAsce57ZiNXBuzOAlOB4uqjuD2waIRgzsfvWfhUL8lxW6q9VVBg3lU63IihXjI2b2vVZuhwOFjsrZEJ_Nl' },
      { id: 'earth-brown', name: 'Velours Brun Terrestre', hex: '#3D3A36', previewUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0XzwKB-YuBlSkVwNNNombN9SuxAoCgf-Ic5Z-gTQk7gQ0CJmzSq3NxbT7PGFjLoVtCO03JIl0uxH0-bgwnrCBTri7Pn_7oaevZQ9Qr2jBbiFK3IdImotI4ZnzLQuHBGJvVHS7kUWG0YPi_tXuq6FXz6ATXb6QMsDP6w_qvzBMg-iff8mDErYtLvJ0aa0RyJBacbm3hF_DbNcH_XGmZ9MhhKjm_qvifh80XqRLFDcPHVJP7gm3-fIQNP3VSU2CPdDg5xh8Sag_p3sI' },
      { id: 'warm-beige', name: 'Velours Beige Chaleureux', hex: '#D1C7BD', previewUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBIICOBi5IbKJ2spEy-knFNd8CzbZUZl_JAJOj-E4qDczpo-yMs8yVrynHXm7e-PyTZMz9I7a8V2ETlLFna7fwH5njveAUELNEfwkmKg6Xk-Rf-HmBR60-hNP3f3UiuTeGwHtqHFfE6edCbS9S4FRatHiJlcO3IDpebhGD1kxypwmeHf2kRta6O1JQLu6QVladd5oJqHbqwnofhpqm3Jop4oc9rekqfb8ZwIUZq1wwMLNc2ckR6Ozuf6q0bUIlIARzfCuYQBWL6EMLj' },
      { id: 'charcoal', name: 'Velours Noir Charbon Carbonisé', hex: '#242424', previewUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqcbGURHZPwT73C398k_N5_DnIHJAyI3NI1mU4MV97VJBIBS4sqbqaWO6E2EEIM9FC6gO7VbTn5mhWjFsODrQuvpJIqtHDz0eNZMC4wXWLXtjUeQ7Go3N8Cq4FDjFz9oQh3F54kbQNgYnt-ZDGvV8vAHEElk8IxPZ_A8y7SSR2mqzzG1o8Nf8JMl3LywnAsce57ZiNXBuzOAlOB4uqjuD2waIRgzsfvWfhUL8lxW6q9VVBg3lU63IihXjI2b2vVZuhwOFjsrZEJ_Nl' }
    ],
    dimensions: '244cm Largeur x 96cm Profondeur x 76cm Hauteur',
    materials: 'Structure en Noyer Massif, Velours Italien d\'Atelier',
    weightCapacity: 'Supporte jusqu\'à 340 kg',
    origin: 'Façonné à la main à Milan, Italie',
    shippingInfo: 'Livraison gants blancs offerte : installation dans la pièce de votre choix, assemblage des pieds et retrait des emballages. Délai standard de 4 à 6 semaines.',
    careInstructions: 'Nettoyage professionnel recommandé. Aspirez chaque semaine à faible puissance avec un embout brosse doux. Maintenir à l\'écart du soleil direct pour préserver la superbe fibre.'
  },
  {
    id: 'aurora-marble-table',
    name: 'Table en Marbre Aurora',
    category: 'Living Room',
    subCategory: 'SALON — TABLES BASSES',
    price: 2100,
    description: 'Une table basse minimaliste reposant sur des socles sculptés en travertin brut. Le veinage organique naturel du marbre de Carrare de première qualité insuffle une superbe présence architecturale et artistique à vos espaces.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaNFBTKOaERfxW3NqdoXSAa9vLM6LD9R2CjSlr648DdCnuDT9-xhozopMbNTX8oiYDuH-82Soo9UmUevKH3yB3flFkWNmkejvPUOmv9NI0Ns-0eGHrzdVlor_nsKhbEC4qrqPQSVkWBdvQvts6dH-WI3dF-GC9gSmBZu3ZhmkBiWi7t-CHSWPCaA5GQMkutP4fzbbHJjOIIZn5gVMCGxJ7CUAd1Pbpyi4xFXKP5wXVYci_DPA7xd6glony0QGQKHuhk40X9urwtuLv',
    additionalImages: [],
    dimensions: '122cm Largeur x 122cm Profondeur x 38cm Hauteur',
    materials: 'Plateau en Marbre de Carrare, Base en Travertin d\'Italie Sculpté',
    weightCapacity: 'Supporte jusqu\'à 160 kg',
    origin: 'Façonné à la main à Carrare, Italie',
    shippingInfo: 'Expédition sécurisée sous coffrage bois avec installation gants blancs obligatoire en raison du poids de la pierre précieuse. Livraison en 3 à 5 semaines.',
    careInstructions: 'Essuyez immédiatement les liquides versés à l\'aide d\'un tissu ultra-doux. Évitez les nettoyants acides, agressifs ou chimiques.'
  },
  {
    id: 'linear-floor-lamp',
    name: 'Lampadaire Linéaire',
    category: 'Office',
    subCategory: 'BUREAU — LUMINAIRES D\'EXCEPTION',
    price: 950,
    description: 'Un lampadaire haut et élancé à la superbe finition noire mate diffusant une lueur chaleureuse et feutrée. Son design asymétrique extrêmement graphique dessine une silhouette sculpturale intemporelle dans la pièce.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD-L9YkzKIg3IKNgDDB9V2-8M-tFLAIJI8MvfjzCvBiuk8ZDihPm6Ee2CwnbJ83v4cAUhAzT4dG30oqL6THDncu9HOBDpF3OH5atWhmMMUEtvJVuySaxDwPHTwykRVvr8u5RjdBvIEDDZdLm_9Guv4Kcgid9i-v9PY5j6fCs14C8zM-B_WOiZM-LX4luGKxzr91BibfTcEBJXte8oZE6pMS2Ogui2UrJU3MoakhVss3yn_JDvIE0Vq0MJGeZa1Th0JmYjPzVs5thChO',
    additionalImages: [],
    dimensions: '183cm Hauteur, socle de 30cm de Diamètre',
    materials: 'Aluminium Anodisé Noir, Laiton Pur Satiné, Module LED Graduable',
    weightCapacity: 'Non applicable',
    origin: 'Fabriqué à l\'unité à Munich, Allemagne',
    shippingInfo: 'Expédié à plat sous triple épaisseur de protection de mousse protectrice. Livraison standard à domicile sous 7 à 10 jours ouvrés.',
    careInstructions: 'Manipulez hors tension. Dépoussiérez doucement à l\'aide d\'un chiffon sec en microfibre sans aucun détergent liquide.'
  },
  {
    id: 'kashmir-wool-throw',
    name: 'Plaid en Laine Cachemire',
    category: 'Bedroom',
    subCategory: 'CHAMBRE — TEXTILES',
    price: 450,
    description: 'Un plaid luxueux tissé à la main combinant des couches neutres d\'avoine et de charbon pour un confort divin. Son tissage texturé introduit une douceur organique hautement réconfortante qui contraste magnifiquement avec le bois et la pierre.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAjJgKjRhXETr5uZONn-q00qXuO6hbf-Tz4ltstfup7x8Cm98jimuWg18Rw95aN2qk3DBxJDFa5BrNlVicQKp38iwSU-4ZhbmQkhaKj33P0ALo_aEauDbkETh4HMuepTFi-X4QVL8OACinsK306fuNSosl2Oop_8w48cJleiiy4m0TkKylyRLkohsw4ugs2DOlHWi7ci9wF5LJNdjVIHOSNkeNBQ1VeB6bUT8uqGnY7hfxlhWo1i2hvMhpQGYfjEJ5OlT48_dIgeHjL',
    additionalImages: [],
    dimensions: '152cm Largeur x 203cm Longueur',
    materials: '100% Cachemire Fin Cardé et Filé à la Main',
    weightCapacity: 'Non applicable',
    origin: 'Métier à tisser manuel au Cachemire, Région du Ladakh',
    shippingInfo: 'Livré dans un sac de protection réutilisable en lin bio brodé d\'Atelier Aura. Expédition sous 3 à 5 jours ouvrés.',
    careInstructions: 'Nettoyage à sec professionnel uniquement. Rangez plié à plat à plat sans poids posé sur le dessus.'
  },
  {
    id: 'serene-oatmeal-bed',
    name: 'Lit Serene Lin Brut',
    category: 'Bedroom',
    subCategory: 'CHAMBRE — LITS D\'EXCEPTION',
    price: 3600,
    description: 'Un lit bas architectural d\'un raffinement rare habillé d\'un lin sauvage fin de couleur avoine. Sa tête de lit capitonnée généreuse impulse une ambiance de sérénité absolue matinale à votre chambre à coucher.',
    imageUrl: '/src/assets/images/luxury_bed_frame_1780428701337.png',
    additionalImages: [],
    dimensions: '213cm Largeur x 223cm Longueur x 107cm Hauteur de tête',
    materials: 'Structure Interne en Chêne Massif, Revêtement Lin Sauvage Respirant',
    weightCapacity: 'Supporte jusqu\'à 385 kg',
    origin: 'Façonné à la main à Copenhague, Danemark',
    shippingInfo: 'Livraison complète gants blancs offerte avec pose dans la chambre, montage, calage et évacuation des emballages. Expédié sous 5 à 7 semaines.',
    careInstructions: 'Brossage léger occasionnel. Nettoyez instantanément les projections ou liquides avec une éponge propre et du savon doux.'
  },
  {
    id: 'sculptural-walnut-chair',
    name: 'Chaise Sculpturale en Noyer',
    category: 'Dining',
    subCategory: 'SALLE À MANGER — ASSISES',
    price: 820,
    description: 'Une chaise qui affirme son caractère sculptural, façonnée à la main dans un superbe noyer sombre de qualité ébénisterie. Son assise vêtue de tissu bouclé crème réconcilie texture douillette et courbes millimétrées.',
    imageUrl: '/src/assets/images/sculptural_chair_1780428721533.png',
    additionalImages: [],
    dimensions: '56cm Largeur x 61cm Profondeur x 81cm Hauteur (Assise 45cm)',
    materials: 'Châssis Noyer Américain Massif, Bouclé Crémeux d\'Italie Haute Tenue',
    weightCapacity: 'Supporte jusqu\'à 135 kg',
    origin: 'Façonné à la main à Milan, Italie',
    shippingInfo: 'Expédiée sous caisse renforcée. Transport offert pour tout ensemble de 4 chaises ou plus. Accostage sous 2 à 3 semaines.',
    careInstructions: 'Dépoussiérez régulièrement à la microfibre sèche. Nettoyez délicatement les boucles. Cire d\'entretien une fois par an.'
  },
  {
    id: 'monolithic-oak-desk',
    name: 'Bureau Monolithe en Noyer Sombre',
    category: 'Office',
    subCategory: 'BUREAU — TABLES DE TRAVAIL',
    price: 2950,
    description: 'Un bureau exécutif monumental taillé dans de magnifiques pièces de noyer foncé de Carélie avec joints ras en laiton poli. Une véritable synergie visuelle et tactile au service de vos aspirations créatrices.',
    imageUrl: '/src/assets/images/monolithic_desk_1780428744017.png',
    additionalImages: [],
    dimensions: '183cm Largeur x 81cm Profondeur x 76cm Hauteur',
    materials: 'Noyer Massif Teinté Sombre, Ferrures Affleurantes Laiton Vieilli',
    weightCapacity: 'Supporte jusqu\'à 200 kg',
    origin: 'Fabriqué à l\'unité à Munich, Allemagne',
    shippingInfo: 'Livraison assurée par deux techniciens spécialisés. Assemblage des piètements et calage précis à domicile compris. Délai de 4 à 6 semaines.',
    careInstructions: 'Utilisez impérativement des sous-verres pour préserver l\'essence poreuse. Cirez avec notre cire d\'abeille Aura chaque saison.'
  }
];
